import { EntityBase } from './entityBase';
import { Injectable} from '@angular/core';
import {
  core, MetadataStore, EntityType, AutoGeneratedKeyType, DataProperty, DataType,
  NavigationPropertyOptions, NavigationProperty
} from 'breeze-client';
import {Role} from "./role";

export class User extends EntityBase {

    id: number;
    username: string;
    email: string;
    firstName: string;
    lastName: string;
    status: string;
  
    roles: Role[];
  
    constructor() {
      super();
    }

    public init(metadataStore:MetadataStore) {

        this.entityType = new EntityType({
          shortName: "User",
          namespace: "TXV",
          defaultResourceName: "User",
          autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
          dataProperties: [
            new DataProperty({
              name: "id",
              dataType: DataType.Int32,
              isPartOfKey: true
            }),
            new DataProperty({
              name: "username",
              dataType: DataType.String
            }),
            new DataProperty({
              name: "email",
              dataType: DataType.String
            }),
            new DataProperty({
              name: "firstName",
              dataType: DataType.String
            }),
            new DataProperty({
              name: "lastName",
              dataType: DataType.String
            }),
            new DataProperty({
              name: "status",
              dataType: DataType.String
            })
          ],
          navigationProperties: [
            new NavigationProperty(<NavigationPropertyOptions>{
              entityTypeName: "UserRoleMap:#TXV",
              associationName: "UserRoleMap_User",
              name: "userRoleMap",
              isScalar: false,
              invForeignKeyNames: ["userId"]
            })
          ]
        });
    
        metadataStore.addEntityType(this.entityType);
        metadataStore.registerEntityTypeCtor('User', User, User.initializer);
        this.entityType.createEntity();
    
      }
      /// [Initializer
      static initializer(entity:User) {
      }

}